name: py37
channels:
  - ralexx
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - xgboost
  - tensorflow
  - pandas
  - numpy
  - scikit-learn
  - h5py
  - multiprocess
  - imbalanced-learn
  - ruptures
  - matplotlib
  - seaborn
  - black
  - pre-commit
