name: dse
channels:
    - defaults
    - anaconda
dependencies:
    - python=3.8
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - scikit-learn-intelex
    - matplotlib
    - ipympl
    - seaborn
    - pylint
    - setuptools
    - toml
    - h5py
    - jupyterlab
    - ipyparallel
    - tqdm
    - pytest
    - numcodecs
    - boto3
    - pynvim
    - pip
    - pip:
        - black
        - modin[all]
        - pre-commit
        - isort
