name: py38
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - numpy
  - xgboost
  - h5py
  - multiprocess
  - matplotlib
  - seaborn
  - black
  - pre-commit
  - setuptools
  - toml
  - isort
