name: er
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - conda-forge::ncurses
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - ipympl
  - seaborn
  - pre-commit
  - pylint
  - identify
  - setuptools
  - toml
  - black
  - isort
  - h5py
  - jupyterlab
  - ipyparallel
  - vim
  - nodejs
  - tqdm
  - pytest
  - ncurses
  - numcodecs
  - pip
