name: er
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.8.3
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pre-commit
  - pylint
  - identify
  - setuptools
  - toml
  - black
  - isort
  - h5py
  - jupyterlab
  - ipyparallel
  - vim
  - nodejs
  - tqdm
  - pytest
