name: py38
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - black=19.10b0
  - isort=4.3.21
  - numpy=1.18.1
  - pandas=1.0.3
  - pre-commit=2.4.0
  - pylint=2.5.2
  - python=3.8.3
  - scipy=1.4.1
  - seaborn=0.10.1
  - setuptools=46.4.0
  - xgboost=1.0.2
  - toml=0.10.1
  - scikit-learn=0.23.1
  - matplotlib=3.2.1
